### ISSUE TITLE
[adblocker-playwright] Object with guid ${arg.guid} was not bound in the connection

### ISSUE THREAD

**Issue by regseb** [ghostery/adblocker#3090]
### Context

- Operating System: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
- Node.js version: 18.14.2

### Code Snippet

```JSON
{
    "name": "testcase",
    "version": "1.0.0",
    "type": "module",
    "dependencies": {
        "@cliqz/adblocker-playwright": "1.26.1",
        "playwright": "1.31.1"
    }
}
```

```javascript
import playwright from "playwright";
import { PlaywrightBlocker } from "@cliqz/adblocker-playwright";

for (let i = 0; i < 10; ++i) {
    console.log(i);
    console.log("playwright.chromium.launch");
    const browser = await playwright.chromium.launch({ slowMo: 250 });
    console.log("browser.newContext");
    const context = await browser.newContext();
    console.log("context.newPage");
    const page = await context.newPage();
    console.log("PlaywrightBlocker.fromPrebuiltAdsAndTracking");
    const blocker = await PlaywrightBlocker.fromPrebuiltAdsAndTracking(fetch);
    console.log("blocker.enableBlockingInPage");
    blocker.enableBlockingInPage(page);
    console.log("page.goto");
    await page.goto("https://playwright.dev/docs/api/class-browser");
    console.log("page.locator");
    await page.locator(`.table-of-contents a[href="#browser-version"]`).click();
    console.log("context.close");
    await context.close();
    console.log("browser.close");
    await browser.close();
}
```

### To reproduce

- Unzip [testcase.zip](https://github.com/ghostery/adblocker/files/10854761/testcase.zip)
- `npm install`
- `DEBUG=pw:browser* node index.js`

```
0
playwright.chromium.launch
  pw:browser <launching> /home/regseb/.cache/ms-playwright/chromium-1048/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-XwfUpN --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=48803 +4ms
  pw:browser [pid=48803][err] [0228/220545.570843:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable. +125ms
browser.newContext
context.newPage
  pw:browser [pid=48803][err] [0228/220545.659964:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process. +86ms
PlaywrightBlocker.fromPrebuiltAdsAndTracking
blocker.enableBlockingInPage
page.goto
page.locator
context.close
browser.close
  pw:browser [pid=48803] <gracefully close start> +7s
  pw:browser [pid=48803] <process did exit: exitCode=0, signal=null> +41ms
  pw:browser [pid=48803] starting temporary directories cleanup +0ms
  pw:browser [pid=48803] finished temporary directories cleanup +6ms
  pw:browser [pid=48803] <gracefully close end> +0ms
1
playwright.chromium.launch
  pw:browser <launching> /home/regseb/.cache/ms-playwright/chromium-1048/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-K21P9m --remote-debugging-pipe --no-startup-window +165ms
  pw:browser <launched> pid=48966 +15ms
  pw:browser [pid=48966] <kill> +5ms
  pw:browser [pid=48966] <will force kill> +0ms
  pw:browser [pid=48966] starting temporary directories cleanup +0ms
  pw:browser [pid=48966] finished temporary directories cleanup +104ms
/home/regseb/tmp/testcase/node_modules/playwright-core/lib/client/connection.js:194
      if (!object) throw new Error(`Object with guid ${arg.guid} was not bound in the connection`);
                   ^

Error: Object with guid handle@bb74f21019e7e4788ef9469e6b1ce03d was not bound in the connection
    at Connection._tChannelImplFromWire (/home/regseb/tmp/testcase/node_modules/playwright-core/lib/client/connection.js:194:26)
    at /home/regseb/tmp/testcase/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:129:20
    at /home/regseb/tmp/testcase/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:108:21
    at Connection.dispatch (/home/regseb/tmp/testcase/node_modules/playwright-core/lib/client/connection.js:153:26)
    at Immediate.<anonymous> (/home/regseb/tmp/testcase/node_modules/playwright-core/lib/inProcessFactory.js:46:83)
    at process.processImmediate (node:internal/timers:476:21)

Node.js v18.14.2
```

### Describe the bug

When I was writing a test case to reproduce the problem, I had a more complex snippet and the error was coming to the `context.close()` of the first iteration. Then by simplifying the snippet, the error would arrive at the `browser.close()` still at the first iteration. Simplifying again, it now arrives at the `chromium.launch()` of the second iteration. If I remove `slowMo` or the `blocker.enableBlockingInPage(page)`, there is no more error on the 10 iterations.

### Related issue

- https://github.com/microsoft/playwright/issues/21210

**Comment by regseb** [comment]
I found a rule that causes the same error: **`##a[href="http://foo.com"]`**

Here are some other rules that fail or pass:

| :x: Fail | :heavy_check_mark: Pass |
| --- | --- |
| `##a[href="http"]` | `##a[href="file"]` |
| `##a[href="https"]` | `##a[href="httpx"]` |
| `##a[href^="http"]` | `##a[href$="http"]` |
| | `##a[title="http"]` |
| | `##link[href="http"]` |
| | `#a[href="http"]` |

---

```JavaScript
import playwright from "playwright";
import { PlaywrightBlocker } from "@cliqz/adblocker-playwright";

for (let i = 0; i < 10; ++i) {
    console.log(i);
    console.log("playwright.chromium.launch");
    const browser = await playwright.chromium.launch({ slowMo: 250 });
    console.log("browser.newContext");
    const context = await browser.newContext();
    console.log("context.newPage");
    const page = await context.newPage();
    console.log("PlaywrightBlocker.parse");
    const blocker = PlaywrightBlocker.parse(`##a[href="http://foo.com"]`); // <-- Line changed!
    console.log("blocker.enableBlockingInPage");
    await blocker.enableBlockingInPage(page);
    console.log("page.goto");
    await page.goto("https://playwright.dev/docs/api/class-browser");
    console.log("context.close");
    await context.close();
    console.log("browser.close");
    await browser.close();
}
```

```Shell
$ node index.js
0
playwright.chromium.launch
browser.newContext
context.newPage
PlaywrightBlocker.parse
blocker.enableBlockingInPage
page.goto
context.close
browser.close
1
playwright.chromium.launch
/home/regseb/tmp/testcase/node_modules/playwright-core/lib/client/connection.js:194
      if (!object) throw new Error(`Object with guid ${arg.guid} was not bound in the connection`);
                   ^

Error: Object with guid handle@60435f1a4e579a9e82f44a76f9a07314 was not bound in the connection
    at Connection._tChannelImplFromWire (/home/regseb/tmp/testcase/node_modules/playwright-core/lib/client/connection.js:194:26)
    at /home/regseb/tmp/testcase/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:129:20
    at /home/regseb/tmp/testcase/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:108:21
    at Connection.dispatch (/home/regseb/tmp/testcase/node_modules/playwright-core/lib/client/connection.js:153:26)
    at Immediate.<anonymous> (/home/regseb/tmp/testcase/node_modules/playwright-core/lib/inProcessFactory.js:46:83)
    at process.processImmediate (node:internal/timers:476:21)

Node.js v18.14.2
```

**Comment by regseb** [comment]
Playwright [responded](https://github.com/microsoft/playwright/issues/22210#issuecomment-1497726490):

> The problem is with this snippet:
> 
> ```js
> page.on("framenavigated", async (frame) => {
>         await frame.locator("span").evaluateAll(() => {});
>         await frame.addStyleTag({ content: "div {}" });
> });
> ```
> 
> Listeners are synchronous in JavaScript, so by the time you reach the second line in this handler, `context.close()` already ran.


According to Playwright, you shouldn't use functions that send commands (e.g. `Locator.evaluateAll()`, `Frame.addStyleTag()`, ...) to the browser in the callback of `page.on("framenavigated", callback)` ([adblocker.ts#L65](
https://github.com/ghostery/adblocker/blob/e330535454563c9394bd1a4f8a78decc7e36ab11/packages/adblocker-playwright/adblocker.ts#L65)). Because if the browser is closed after sending the command and before the response: it's normal that the application crashes.

Personally, I think this behavior is a bug. Playwright should stop the running commands when the browser is closed.

¯\\\_(ツ)\_/¯

**Comment by regseb** [comment]
I no longer have this bug since `playwright` [`1.33.0`](https://github.com/microsoft/playwright/releases/tag/v1.33.0) (tested with `@cliqz/adblocker-playwright` `1.26.12`). See https://github.com/microsoft/playwright/issues/22210#issuecomment-1866045256
