### ISSUE TITLE
Main process minimization with Webpack

### ISSUE THREAD

**Issue by glani** [ghostery/adblocker#3209]
Minimization of the application in webpack causes the problem with

const PRELOAD_PATH = require.resolve('@cliqz/adblocker-electron-preload');

as result in the minified code:

(node:87637) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure from
    at Ci.enable (/Applications/SMBActApp.app/Contents/Resources/app/app-native/main.js:3994:85)
    at Di.enableBlockingInSession (/Applications/SMBActApp.app/Contents/Resources/app/app-native/main.js:4066:93)
    at c.<anonymous> (/Applications/SMBActApp.app/Contents/Resources/app/app-native/main.js:16148:63)
    at Generator.next (<anonymous>)
    at n (/Applications/SMBActApp.app/Contents/Resources/app/app-native/main.js:16058:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

original call is before minimization:

this._win = new BrowserWindow({

      },
    });
    if (this._blockMetadata.blockAds) {
      blocker.enableBlockingInSession(this._win.webContents.session);
    }

the problem is on these two lines:
https://github.com/ghostery/adblocker/blob/7f652911ad40b2572f10144091bc7e413caee270/packages/adblocker-electron/adblocker.ts#L90

https://github.com/ghostery/adblocker/blob/7f652911ad40b2572f10144091bc7e413caee270/packages/adblocker-electron/adblocker.ts#L18

looks like workaround to put: loadCosmeticFilters = false in configuration.

**Comment by seia-soto** [comment]
Hi there,

I am aware of this issue created in 2023, which is not up-to-date. Sorry for being late. However, I'm leaving an answer here for the future reference purpose. Due to the electron limitation, I think you should preserve the path to the prelude script unless we fully change the injection method. We're currently using preload scripts to inject cosmetics.

By copying the script into the preload path where script presence is actually expected: e.g. `node_modules/ghostery/adblocker-electron-preload/...` would help.

This can be solved by tweaking build configuration from the view of 2025. However, we'd welcome the alternative workaround which may fit better to everyone in the future. Please, re-open the issue in case you're still having a problem or have a better approach.

We appreciate your interest to our library.

Best
