### ISSUE TITLE
Automatic asset update and codebook generation are broken

### ISSUE THREAD

**Issue by seia-soto** [ghostery/adblocker#4397]
https://github.com/ghostery/adblocker/actions/runs/11543403951

**Comment by seia-soto** [comment]
The error code is not reproducible on local environment.

```sh
...
aa@MacBookPro adblocker % echo $?                          
0
```

**Comment by chrmod** [comment]
the full error is
```
 [build:cosmetic-selector] file:///home/runner/work/adblocker/adblocker/node_modules/@remusao/counter/dist/esm/index.js:33
[build:cosmetic-selector]         this.map.set(key, this.get(key) + n);
[build:cosmetic-selector]                  ^
[build:cosmetic-selector] 
[build:cosmetic-selector] RangeError: Map maximum size exceeded
[build:cosmetic-selector]     at Map.set (<anonymous>)
[build:cosmetic-selector]     at Counter.incr (/home/runner/work/adblocker/adblocker/node_modules/@remusao/counter/src/index.ts:41:14)
[build:cosmetic-selector]     at addCounts (/home/runner/work/adblocker/adblocker/node_modules/@remusao/smaz-generate/src/index.ts:95:19)
[build:cosmetic-selector]     at generate (/home/runner/work/adblocker/adblocker/node_modules/@remusao/smaz-generate/src/index.ts:183:3)
[build:cosmetic-selector]     at generateCodebook (/home/runner/work/adblocker/adblocker/packages/adblocker/tools/generate_compression_codebooks.ts:135:20)
[build:cosmetic-selector]     at <anonymous> (/home/runner/work/adblocker/adblocker/packages/adblocker/tools/generate_compression_codebooks.ts:142:20)
[build:cosmetic-selector] 
[build:cosmetic-selector] Node.js v22.4.1
[build:cosmetic-selector] yarn run codebook-cosmetic-selector exited with code 1
```

It's related to the ngram size that is too big for the block lists currently in use. But as we cannot reproduce locally it may mean that the block list have removed the problematic filter.
