### ISSUE TITLE
Overflow error when loading uBO quick fix list

### ISSUE THREAD

**Issue by sammacbeth** [ghostery/adblocker#4424]
As of today, I get the following error when loading uBlock Origin's `quick-fixes.txt` list:
```
Uncaught RangeError: Overflow: input needs wider integers to process
    at error (/node_modules/@ghostery/adblocker/dist/commonjs/punycode.js:59:11)
    at encode (/node_modules/@ghostery/adblocker/dist/commonjs/punycode.js:268:13)
    at sizeOfUTF8 (l/node_modules/@ghostery/adblocker/dist/commonjs/data-view.js:95:52)
...
```

This seems likely to be related to the most recent commits:
- https://github.com/uBlockOrigin/uAssets/commit/f7d58e3bf2f916d50201a95234608392fc9ae7a7
- https://github.com/uBlockOrigin/uAssets/commit/020d362490aa796d64f69639227b50b8fc2de73e

Steps to reproduce:
```javascript
const { FiltersEngine } = require('@ghostery/adblocker')
await FiltersEngine.fromLists(fetch, ["https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt"])
```

**Comment by chrmod** [comment]
Looks like a limitation of punycode:
```js
import punycode from "punycode";

const lines = (
  await (
    await fetch(
      "https://raw.githubusercontent.com/uBlockOrigin/uAssets/f7d58e3bf2f916d50201a95234608392fc9ae7a7/filters/quick-fixes.txt"
    )
  ).text()
).split("\n");

for (const line of lines) {
  try {
    punycode.encode(line);
  } catch (e) {
    console.error(e);
    console.warn(line.length);
  }
}
```
